### PR TITLE
[Shared] Implement dynamic cast for Superclass::as_subclass using RTTI data

### LINKED ISSUE #194: `WorldChrMan::chr_ins_by_handle()` returns None for the main player
This prints `false`

```rust
if let Some(ref main_player) = world_chr_man.main_player {
    let main_player_handle = main_player.chr_ins.field_ins_handle;

    let main_player_exists = world_chr_man
        .chr_ins_by_handle(&main_player_handle)
        .is_some();

    println!("{:?}", main_player_exists);
}
```

I believe this is related to how `ChrSet<T>` verifies members are subclasses of `T` as of #157, since the main player is a `PlayerIns` instead of a `ChrIns`. That said, I'm not sure how this superclass system works so idk. It works if I make `SuperClass::is_subclass` always return true

(To reproduce, try running the invoke_esd example. It prints ChrError when `T` is pressed)

### PR DESCRIPTION
**Pull request by ThomasJClark**
Check the base class array using RTTI when dynamic casting an object using the superclass trait

Testing:

```rust
let program = &Program::current();

let cols: Vec<(&str, &RTTICompleteObjectLocator)> = vec![
    ("FieldInsBase", program.derva(0x32ca188).unwrap()),
    ("ChrIns", program.derva(0x32cd0e0).unwrap()),
    ("PlayerIns", program.derva(0x32e4b30).unwrap()),
    ("CSBulletIns", program.derva(0x32ca0b8).unwrap()),
    ("WorldChrManImp", program.derva(0x32d67c8).unwrap()),
];

for (subclass_name, subclass_col) in cols.iter() {
    for (baseclass_name, baseclass_col) in cols.iter() {
        if subclass_name != baseclass_name
            && is_base_class(program, baseclass_col, subclass_col)
        {
            println!("{} is a {}", subclass_name, baseclass_name);
        }
    }
}
```

image

Fixes #194

### CODE REVIEW

File: crates/shared/src/subclass.rs
Comment (nex3) [inline crates/shared/src/subclass.rs]: You'll need to modify the safety guarantees required by the `Superclass` and `Subclass` traits to not only require that the first element is a pointer to a vtable, but that that vtable follows the MSVC RTTI conventions.

**Review by nex3 — CHANGES_REQUESTED** [review]

File: crates/shared/src/subclass.rs [hunk 1]
```diff
@@ -91,7 +102,8 @@ pub unsafe trait Superclass: Sized {
 /// In order to implement this for a struct, you must guarantee:
 ///
 /// * The struct uses C-style layout.
-/// * An initial subsequence of the struct is a valid isntance of `T`.
+/// * The first element of the struct is a pointer to a vtable for a class with MSVC RTTI.
```
Comment (nex3) [inline crates/shared/src/subclass.rs]: This is actually not necessary here, now that I think about it—the final guarantee already implies it (since an initial subsequence is a superclass which already has to begin with a MSVC VMT).

File: crates/shared/src/rtti.rs [hunk 2]
```diff
@@ -113,6 +116,32 @@ pub fn vftable_classname(program: &Program, vftable_va: usize) -> Option<String>
...
+    let class_hierarchy_descriptor: &RTTIClassHierarchyDescriptor = program
+        .derva(class_col.class_descriptor)
+        .expect("Class descriptor not in executable");
+
+    let base_class_array: &[Rva] = program
+        .derva_slice(
+            class_hierarchy_descriptor.base_class_array,
+            class_hierarchy_descriptor.num_base_classes as usize,
+        )
+        .expect("Base class array not in executable");
```
[the remark this answers is not in the document]
Comment (vswarte) [reply crates/shared/src/rtti.rs]: Feel free to unwrap_or_default() in `is_subclass` btw,otherwise the error handling met get tedious

**Review by nex3 — APPROVED** [review]
